Added project for code review
zhannapopenko/Genesis-Frontend-School-Homework-1 pull request #1
Opened 2021-12-24 11:53 UTC by zhannapopenko

2021-12-24 23:06 UTC, EugeniaKolodeichuk commented
Отличный код! Структурированный, стиль написания кода один, хорошо отформатирован - есть отступы между семантическими блоками, без лишних комментариев. Замечаний и правок - нет)

2021-12-30 14:30 UTC, Margot-Jones requested changes
Классная структура проекта, вынесены стили в отдельные файлы, логическое построение, использованы современные методы работы с React.

2021-12-30 14:30 UTC, Margot-Jones commented on src/components/User/UserFeed/UserFeed.jsx
> +  }
Лучше не использовать if-else, если последнее из условий не рендерит необходимый блок, в практике чаще встречается для таких случаев логические операторы feed && <Box>...</Box> или для else прописать просто null.

2021-12-30 14:30 UTC, Margot-Jones commented on src/components/User/UserInfo/UserInfo.jsx
> +      <Divider sx={{ marginBottom: "0.5rem" }} />
Инлайновые стилей надо по максимуму избегать.

2021-12-30 14:30 UTC, Margot-Jones commented on src/layout/Header.jsx
> +            <strong>Tik Tuk</strong>
В идеале надо застайлить текст, потому что тег strong используется для семантики.

2021-12-30 14:30 UTC, Margot-Jones commented on src/numberFormatting.js
> +}
https://v8.dev/features/intl-numberformat#notation
для этого существует встроенный объект intl, одна из его возможностей - форматировать числа.

2021-12-30 14:30 UTC, Margot-Jones commented on src/pages/Profile.jsx
> +  return (
мне как человеку читающему код не удобно что куча return, я бы прописала тернарные операторы.

2021-12-30 14:30 UTC, Margot-Jones commented on src/services/axios/index.js
> +    "x-rapidapi-key": "c17160964emsh53c95fe98847290p1030d7jsne22e88c7eb61",
лучше не делиться личными данными, как в данном случае ключом, для этого его можно вынести в отдельный файл .env

2021-12-31 09:33 UTC, zhannapopenko commented on src/layout/Header.jsx
> +            <strong>Tik Tuk</strong>
Я заміню strong на b, замість використання стилів, так код буде легше сприйматись, він потрібний лише для того, щоб зробити текст жирним

2021-12-31 10:44 UTC, zhannapopenko commented on src/pages/Profile.jsx
> +  return (
Тернарний оператор не зручно використовувати, коли коду багато, його складно читати

2021-12-31 11:46 UTC, zhannapopenko commented on src/services/axios/index.js
> +    "x-rapidapi-key": "c17160964emsh53c95fe98847290p1030d7jsne22e88c7eb61",
Так, дякую, це важливе виправлення

2021-12-31 12:07 UTC, zhannapopenko commented on src/components/Preloader.jsx
> +      <img src={Spinner} alt="loader" />
дякую)

2021-12-31 15:58 UTC, merged